@dev=http://localhost:8080
# @endpoint=https://static.smallsaas.cn
@endpoint=https://house.cloud.smallsaas.cn


###文件查找
GET {{dev}}/api/js/v1/132/findfiles




###
#http://localhost:8080/api/doswagger/download/rss/rss图片集测试用例.http