# @endpoint=http://localhost:8080

@endpoint=http://house.cloud.smallsaas.cn

# 查看图文列表
GET {{endpoint}}/api/u/rss/master


### 查看图文详情
GET {{endpoint}}/api/u/rss/master11

### 修改rss 并重新解析 imageStyle 图片风格  imageContainer 图片容器风格 imageExpression 图片排列表达式
PUT {{endpoint}}/api/u/rss/master/18
{
    "createTime": null,
    "extra": null,
    "id": "18",
    "name": "228fb114-fa35-408c-bf08-761d0470a772",
    "note": null,
    "orgId": null,
    "rssItemList": [
      {
        "createTime": "2022-10-20 17:35:30",
        "fontSize": 20,
        "fontWeight": true,
        "id": "61",
        "imageContainer": "H3",
        "imageExpression": "|--[1,2]",
        "imageRatio": null,
        "imageSort": "|--",
        "imageStyle": "H3",
        "lineHeight": 20,
        "note": null,
        "pictures": null,
        "pid": "18",
        "rssComponentList": [
          {
            "componentFormInputOption": null,
            "componentName": "table",
            "componentOption": null,
            "componentTag": null,
            "componentType": "imageUpload",
            "css": null,
            "cssName": null,
            "imageName":"img-sofa-ren",
            "iamgeList":"['url:hgdhgdhgd.png',]",
            "id": "88",
            "name": null,
            "rssComponentPropList": [
              {
                "componentId": "88",
                "dataType": null,
                "id": "159",
                "optionName": null,
                "propDefaultValue": "户型",
                "propName": null,
                "propTips": null
              },
              {
                "componentId": "88",
                "dataType": null,
                "id": "159",
                "optionName": null,
                "propDefaultValue": "宽",
                "propName": null,
                "propTips": null
              }
            ],
            "rssItemId": "61"
          }
        ],
        "sortNumber": 1,
        "status": 1,
        "title": "家电齐全，简单装修",
        "updateTime": null
      },
      {
        "createTime": "2022-10-20 17:35:30",
        "fontSize": 14,
        "fontWeight": false,
        "id": "62",
        "imageContainer": null,
        "imageContainerJson": null,
        "imageExpression": null,
        "imageRatio": null,
        "imageSort": null,
        "imageStyle": null,
        "imageStyleJson": null,
        "lineHeight": 20,
        "note": null,
        "pictures": "[]",
        "pid": "18",
        "rssComponentList": [
          {
            "componentFormInputOption": null,
            "componentName": "tag",
            "componentOption": null,
            "componentTag": null,
            "componentType": "tag",
            "css": null,
            "cssName": null,
            "id": "89",
            "name": null,
            "rssComponentPropList": [
              {
                "componentId": "89",
                "dataType": null,
                "id": "160",
                "optionName": null,
                "propDefaultValue": "光线好",
                "propName": null,
                "propTips": null
              },
              {
                "componentId": "89",
                "dataType": null,
                "id": "161",
                "optionName": null,
                "propDefaultValue": "阳光充足",
                "propName": null,
                "propTips": null
              },
              {
                "componentId": "89",
                "dataType": null,
                "id": "162",
                "optionName": null,
                "propDefaultValue": "近地铁",
                "propName": null,
                "propTips": null
              }
            ],
            "rssItemId": "62"
          }
        ],
        "sortNumber": 1,
        "status": 1,
        "title": ";;; 光线好,阳光充足,近地铁",
        "updateTime": null
      }
    ],
    "sortNumber": null,
    "status": 1,
    "tagIds": null,
    "tags": null,
    "updateTime": null,
    "uuid": "228fb114-fa35-408c-bf08-761d0470a772"
  }



### 新增图文 imageStyle 图片风格  imageContainer 图片容器风格 imageExpression 图片排列表达式
POST {{endpoint}}/api/u/rss/master
[
      {
        "fontSize": 20,
        "fontWeight": true,
        "imageContainer": "H3",
        "imageExpression": "|--[1,2]",
        "imageRatio": null,
        "imageSort": "|--",
        "imageStyle": "H3",
        "lineHeight": 20,
        "note": null,
        "pictures": null,
        "sortNumber": 1,
        "status": 1,
        "title": "家电齐全，简单装修",
      },
      {
        "fontSize": 14,
        "fontWeight": false,
        "id": "58",
        "imageContainer": null,
        "imageContainerJson": null,
        "imageExpression": null,
        "imageRatio": null,
        "imageSort": null,
        "imageStyle": null,
        "imageStyleJson": null,
        "lineHeight": 20,
        "note": null,
        "pictures": "[]",
        "pid": "11",
        "sortNumber": 1,
        "status": 1,
        "title": ";;; 光线好,阳光充足,近地铁",
      }
    ]





### 删除图文
DELETE {{endpoint}}/api/u/rss/master/1


###查看css 风格列表
GET {{endpoint}}/api/u/rss/css/cssStyle

##查看css 风格详情
GET {{endpoint}}/api/u/rss/css/cssStyle/1


###删除css 风格
DELETE {{endpoint}}/api/u/rss/css/cssStyle/1

  
### 标签列表
GET {{endpoint}}/api/u/rss/tag?rssId=11


# 修改标签 和添加标签
POST {{endpoint}}/api/u/rss/tag/bulk
[
    {
      "id": "11",
      "isPrimary": 0,
      "rssId": "13",
      "selected": true,
      "sortOrder": 1,
      "tagName": "联通5G代理",
      "tagType": "Rss"
    },
    {
      "id": "12",
      "isPrimary": 0,
      "rssId": "13",
      "selected": true,
      "sortOrder": 1,
      "tagName": "跨境短信",
      "tagType": "Rss"
    }
]

### 添加单个标签
POST {{endpoint}}/api/u/rss/tag
{
      "id": "11",
      "isPrimary": 0,
      "rssId": "14",
      "selected": true,
      "sortOrder": 1,
      "tagName": "联通5G代理",
      "tagType": "Rss"
    }

### 删除单个标签
DELETE {{endpoint}}/api/u/rss/tag/{id}/{rssId}


